### ISSUE TITLE
Ignore bins: dictionary changed size during iteration

### ISSUE THREAD

**Issue by PawelWiecha** [mciepluc/cocotb-coverage#1]
Adding ignore bins to CoverCross instance gives a runtime error mentioned in the topic. The culprit is coverage.py, line 342, `for x_bins in self._hits.keys():`. According to SO [https://stackoverflow.com/a/11941855/2922946](url) in Python 3 `keys` returns an iterator instead of a list.
Encapsulating  with `list` solved this problem for me `list(self._hits.keys())`.

**Comment by mciepluc** [comment]
fixed
