### ISSUE TITLE
Sphinx setup for documentation

### ISSUE THREAD

**Issue by cmarqu** [mciepluc/cocotb-coverage#2]
It would be nice if there was a Sphinx setup for documentation of this extension (even if it is not automatically hooked up to readthedocs).
The ``automodules`` Sphinx plugin could be used to easily extract all classes and methods etc., but the following issue from cocotb also applies here then: https://github.com/potentialventures/cocotb/issues/715

**Comment by mciepluc** [comment]
documentation set up
