### ISSUE TITLE
Error in merging two or more files

### ISSUE THREAD

**Issue by Losiek** [mciepluc/cocotb-coverage#31]
Following error is occurs when merging two or more files with function 
`cov.merge_coverage(print, "cov.xml", "cov_1.xml", "cov_2.xml")`

Error:
> ~/.conda/envs/p_env/lib/python3.7/site-packages/cocotb_coverage/coverage.py in merge_element(db)
   1082                     parent_hits_threshold = int(
   1083                         name_to_elem[parent_name].attrib['at_least'])
-> 1084                     if (hits_orig < parent_hits_threshold
   1085                         and hits_orig+hits >= parent_hits_threshold):
   1086                         update_parent(name=abs_name, bin_update=True,
> UnboundLocalError: local variable 'hits_orig' referenced before assignment

**Comment by mciepluc** [comment]
@Losiek please confirm it's fixed and close

**Comment by Losiek** [comment]
Works, thanks.
