### ISSUE TITLE
Version 1.1.dev in pypi 

### ISSUE THREAD

**Issue by tsengr0916** [mciepluc/cocotb-coverage#44]
Is this 1.1.dev version available from https://pypi.org/project/cocotb-coverage? If not, can you please add in there? The issue is the 1.0.0 version does not work with the solve_order correctly. I have to use 1.1.dev, but our IT support said it will be very difficult to pull in the open source module that is not  from pypi.org. 

Thanks,
Richard

**Comment by themperek** [comment]
If @mciepluc agree I can upload `1.1.dev0`

**Comment by mciepluc** [comment]
@tsengr0916 yeah I think it is a good idea anyway to make the pre-relase. I uploaded the package and description on the main page to use ```1.1.dev0``` as recommended.

**Comment by tsengr0916** [comment]
Thanks guys. I see this is updated: https://github.com/mciepluc/cocotb-coverage, but here is not: https://pypi.org/project/cocotb-coverage/

What is the process to release to the pypi ? If the former link used for development testing?

**Comment by mciepluc** [comment]
@tsengr0916 `1.1.dev0` is not a stable release, so it will not be present under the link you provided. It is here https://pypi.org/project/cocotb-coverage/1.1.dev0/
