### ISSUE TITLE
Save coverage database in XML format

### ISSUE THREAD

**Issue by mciepluc** [mciepluc/cocotb-coverage#5]
coverage_db object should be exportable to XML format.
There should be also an option for merging coverage databases (for sure something like this exists).
Examine also other coverage databases formats, if it makes sense (UCIS?).

**Comment by mciepluc** [comment]
xml database save option added via #15 , still merging to be added

**Comment by pwiecha** [comment]
XML database merge + export improvements added in #17 
Pretty print format added in #19

**Comment by mciepluc** [comment]
closed via #19
