### ISSUE TITLE
How to report merged coverage?

### ISSUE THREAD

**Issue by jahagirdar** [mciepluc/cocotb-coverage#52]
Related to #22,

Each of my testcase exports its coverage data in an XML file.
At the end of the regression I call a script which finds all 'coverage.xml' file and calls
`merge_coverage(log.info, "functional_coverage.xml", *all_files)`

Now the next step is to call

`{some coverage_db}.report_coverage()`

Looking at the code it looks like the merged_db is local to the function and cannot be used.
Is there some other way to report the merged data?

**Comment by mciepluc** [comment]
@jahagirdar 
```merge_coverage``` is a function that is used to merge databases in XML/YAML format. It is not related to the ```CoverageDB``` datatype. It returns a merged database also in XML/YAML format.

You can use any external XML/YAML viewer to report the database in a readable format, e.g. https://www.xmlviewer.org/
