### ISSUE TITLE
report_coverage() does not accept a logger object as documented

### ISSUE THREAD

**Issue by jonpovey** [mciepluc/cocotb-coverage#62]
`report_coverage()` requires a `logger` argument documented as:

> logger (func) – a logger object.

But it does not accept a "logger object" as described in https://docs.python.org/3/library/logging.html
Actually what it wants is a function such as `logger.info` or `print`.
Suggest changing this documentation line to something less confusing, perhaps something like:

> logger (func) - a logging function (e.g. logger.info)

**Comment by mciepluc** [comment]
thanks, fixed
