### ISSUE TITLE
Access to `coverage_db['top'].detailed_coverage` field is failed.

### ISSUE THREAD

**Issue by glkclass** [mciepluc/cocotb-coverage#66]
`CoverItem` class contains `detailed_coverage` property and it can be accessed accordingly to spec. But trying to address it (for instance: `coverage_db['top'].detailed_coverage`) leads to fail. The cause of exception is using `append()` method for a dict in `CoverItem` code:
```        
coverage = {}
for child in self._children:
    coverage.append(child.detailed_coverage)
```

**Comment by mciepluc** [comment]
@glkclass thanks a lot for your contributions!. Could you please prepare a unit test for this (simply add a test function to the existing tests).
