### ISSUE TITLE
 How to use random seed in crv?

### ISSUE THREAD

**Issue by hardy-hq** [mciepluc/cocotb-coverage#83]
Can cocotb_coverage cocotb_crv realize random seed? How to use random seed?

**Comment by mciepluc** [comment]
As the numpy library is used for random generation, you can simply use seed function from numpy.
https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html

**Comment by mciepluc** [comment]
random.seed is not a numpy function. Please use numpy.random.seed instead. You probably use this one:
https://docs.python.org/3/library/random.html

**Comment by hardy-hq** [comment]
thanks
