### ISSUE TITLE
Add Sphinx code to handle epydoc formatting in constraint.py

### ISSUE THREAD

**Issue by cmarqu** [mciepluc/cocotb-coverage#9]
See also https://github.com/python-constraint/python-constraint/issues/4

**Comment by cmarqu** [comment]
Sounds fine to me. We can then work together with them to get their docs as Sphinx on the web, and use the intersphinx extension for cross-references.

**Comment by mciepluc** [comment]
@cmarqu is anything more to be done regarding this issue in cocotb-coverage? As python-constraint is now separated package, do you think any cross-references are needed?

**Comment by cmarqu** [comment]
Cross-references are not needed, so I'm closing this.
We can always pick this up in the future once they have a Sphinx setup on the web.
